version: '3.7'
services:
  app:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
  db:
    image: mongo:latest
    volumes:
      - "~/Workspace/docker/MongoDB:/data/db"

